services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: love2bazzar-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - love2bazzar

  mongo:
    image: mongo:7
    container_name: love2bazzar-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - love2bazzar

volumes:
  mongo-data:

networks:
  love2bazzar:
    driver: bridge
